# Generated by Django 4.2.5 on 2023-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Bio Maths', 'Bio Maths'), ('VHSE', 'VHSE')], max_length=50)),
                ('purpose', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return'), ('Reporting', 'Reporting'), ('Placements', 'Placements')], max_length=50)),
                ('notebook', models.BooleanField(default=False)),
                ('pen', models.BooleanField(default=False)),
                ('paper', models.BooleanField(default=False)),
            ],
        ),
    ]
