# Generated by Django 4.2.5 on 2023-09-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_department_course_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Bio Maths', 'Bio Maths'), ('VHSE', 'VHSE')], max_length=100),
        ),
    ]
