# Generated by Django 4.2.5 on 2023-09-12 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Bio Maths', 'Bio Maths'), ('VHSE', 'VHSE')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
