# Generated by Django 4.2.5 on 2023-09-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_remove_student_notebook_remove_student_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='material',
            field=models.BooleanField(choices=[('Notebook', 'Notebook'), ('pen', 'pen'), ('paper', 'paper')], default=False),
        ),
    ]
