# Generated by Django 4.2.5 on 2023-09-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_alter_student_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='material',
            field=models.BooleanField(default=False),
        ),
    ]
