# Generated by Django 4.2.5 on 2023-09-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_alter_student_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='material',
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='pen',
            field=models.BooleanField(default=False),
        ),
    ]
